### ISSUE TITLE
Fix lag when a lot of track

### ISSUE THREAD

**Issue by flyingrub** [cozy-labs/cozy-music#18]

**Comment by m4dz** [comment]
We should use `class` and flexbox `order` property to dynamically hide/show and re-sort tracks in ist view using CSS exclusively instead of rebuild a full list view when swicthing.

**Comment by flyingrub** [comment]
I think we have multiple options here :
- keep a playlist model and refactor it to only contains trackID
- keep a playlist model and use the playlist attribute of track
- remove the playlist model and use the playlist attribute of track

**Comment by m4dz** [comment]
I'm not sure to understand why you want to keep track of playlist in this context… 🤔

**Comment by flyingrub** [comment]
With a playlist model we have a title attribute and an id that we can use as class to identify a playlist
