### ISSUE TITLE
Allow to import files from Cozic

### ISSUE THREAD

**Issue by clochix** [cozy-labs/cozy-music#34]
As [requested on the forum](https://forum.cozy.io/t/cozy-music-files-not-found/2397). Some user used Cozic, it would be nice to allow to synchronize Music with the collections already available in Cozic.

**Comment by m4dz** [comment]
Music should import previous Cozic format. Is it what you have in mind, or are you thinking about another feature?

**Comment by clochix** [comment]
I have nothing in mind (you should know it :-P).
According to the user testimony, it looks like import of previous files from Cozic failed.
