### ISSUE TITLE
Improve first use experience

### ISSUE THREAD

**Issue by clochix** [cozy-labs/cozy-music#35]
When first opening the application, a lot of users doesn't understand they have to click on « synchronize » to import files from File. We should add a quick tutorial.
Also maybe synchronizing at first start / each time the application start?

**Comment by flyingrub** [comment]
I think we can now remove the button and do it automatically after each start yes :) @m4dz  ?

**Comment by m4dz** [comment]
Agree :+1:

**Comment by flyingrub** [comment]
https://github.com/cozy-labs/cozy-music/commit/5d3d3386d040fb99dcc9c34042cc3da51f7e4c7b fixed :)
