### ISSUE TITLE
Handle ID3 tag

### ISSUE THREAD

**Issue by flyingrub** [cozy-labs/cozy-music#39]

**Comment by clochix** [comment]
As requested in [this thread](https://forum.cozy.io/t/de-nouvelles-applications-pour-votre-cozy-donnez-nous-votre-avis-sur-la-communication-entre-applications/2399/4).

Note that this could be done in the application itself, client-side, or in some server-side application like Files itself.

**Comment by flyingrub** [comment]
https://github.com/cozy/cozy-data-system/pull/247

**Comment by clochix** [comment]
Thanks @flyingrub !
Once it has been merged and published, could you add a comment in the thread on the forum?
