### ISSUE TITLE
Add tooltips on UI elements

### ISSUE THREAD

**Issue by m4dz** [cozy-labs/cozy-music#41]
We should display tooltips to add informations about Ui elements. Maybe use [aria tips](https://m4dz.github.io/aria-tips/) to do this?

**Comment by flyingrub** [comment]
http://www.w3schools.com/tags/att_global_title.asp ? 

Ex : https://github.com/cozy-labs/cozy-music/blob/master/app/views/templates/track.jst#L18

**Comment by m4dz** [comment]
1/ never ever show me a link to w3school again :stuck_out_tongue_closed_eyes: 
2/ aria-tips is already in use in Email (and other cozy apps) and offer a better support for a11y devices (but I definitely need to package it to npm #myFault)

Meanwhile, `title` attr can be a quick and dirty solution :smiley:

**Comment by flyingrub** [comment]
https://github.com/cozy-labs/cozy-music/commit/fc4b2857c60b8dd2e6acf46e6db56a0a83b70955
