### ISSUE TITLE
Icon is too big on self hosted Cozy

### ISSUE THREAD

**Issue by pierrevdk** [cozy-labs/cozy-music#42]
Hi!

The icon is too big on the self hosted Cozy (see screenshot attached).
![capture d ecran 2016-04-29 a 15 03 43](https://cloud.githubusercontent.com/assets/3509517/14916733/98ac8e2a-0e1b-11e6-941d-666502ce6bfc.png)

**Comment by rgarrigue** [comment]
Sort of +1, I don't hve any icon displaying on my rpi2 cozy

EDIT : my bad, there's an icon displaying once installed. But in the /#applications I've no icon for the installation. And no description either.

**Comment by clochix** [comment]
Maybe @m4dz fixed this in the next version of Home that should be released soon (yes, icons are stored in Home)

**Comment by m4dz** [comment]
Yep, confirmed :smile:
