### ISSUE TITLE
Music ID3 info

### ISSUE THREAD

**Issue by rgarrigue** [cozy-labs/cozy-music#43]
Hi

I've tried to edit mp3 properties, there was no reaction. 
I'm not sure Music is displaying ID3 info too, my column artist / track / duration are empty

Feature idea : propose a button for cozy music to fill property like MusicBrainz Picard, by hashing / asking a web database about it

Thanks & regards

**Comment by flyingrub** [comment]
https://github.com/cozy-labs/cozy-music/issues/39 duplicate
Those menu are hidden in the next maj because unimplemented for now.
