### ISSUE TITLE
User'n'group is cozy-cozy

### ISSUE THREAD

**Issue by rgarrigue** [cozy-labs/cozy-music#50]
On my raspberry pi2, installed like last week

```
id
uid=1017(cozy-cozy-music) gid=1017(cozy-cozy-music) groups=1017(cozy-cozy-music)
```

**Comment by m4dz** [comment]
Hmmm, fun… @frankrousseau, @poupotte, any idea?

**Comment by clochix** [comment]
Well, don't now if it's a bug. In controller, when installing an application, we create its user by [prefixing the application name](https://github.com/cozy/cozy-controller/blob/master/server/lib/app.coffee#L36) by `cozy`.

@rgarrigue is this really an issue for you?

**Comment by rgarrigue** [comment]
No it's not, that's just cosmetic stuff I signal while I'm around :)

**Comment by clochix** [comment]
In fact, the application has been renamed from `cozy-music` to `music` in its own manifest, but not [inside our app store](https://github.com/cozy/cozy-registry/blob/master/apps/music.json#L3), and the later name override the one from `package.json`.
Maybe should we update our registry, but I fear renaming an application may cause some issue.

**Comment by frankrousseau** [comment]
Let's try?

**Comment by jsilvestre** [comment]
I'm closing since it's not an actual problem!
