### ISSUE TITLE
Re-enable shuffle

### ISSUE THREAD

**Issue by m4dz** [cozy-labs/cozy-music#53]
As we recently disable the shuffle feature (#47), we should re-enable it with some modifications. As @flyingrub mentions, SoundCloud and Youtube _resort_ the upNext playlist when doing a shuffle, but users seems to expect a player simply keep the order but pick a random track into the list (and don't care if a track can be selected multiple times).

I suggest we re-implement the feature this way: pick a track randomly in the upNext playlist when `next` event is triggered rather than choosing the next one into the list. This way, the shuffle can be enabled (pick randomly) / disabled (pick next one) rather than a one way action. Plus, we can keep a list of previously played tracks and ignore them in the random pick, so if forces the playlist to be entirely palyed one time before picking a track twice.

@flyingrub, @poupotte, @kelukelu : any thoughs about it?

**Comment by flyingrub** [comment]
https://github.com/cozy-labs/cozy-music/pull/76
