### ISSUE TITLE
Do not remove the song being played when reseting the up next list

### ISSUE THREAD

**Issue by pierrevdk** [cozy-labs/cozy-music#99]
When I reset the up next list, it also deletes the music I am currently listening, which is a bit frustrating. 

Spotify separates the sound being played from the upcoming songs, this could be something to do on Music as well.

<img width="859" alt="Spotify Up Next" src="https://cloud.githubusercontent.com/assets/3509517/17693790/12426f4a-63a1-11e6-9cdd-2983a0d41c3a.png">

**Comment by flyingrub** [comment]
https://github.com/cozy-labs/cozy-music/pull/107
